import sharp from "sharp";
import { readdir, mkdir, writeFile, stat } from "node:fs/promises";
import { join, parse, extname } from "node:path";

const SOURCE_DIR = "D:/BaiduNetdiskDownload/青木乐队";
const OUTPUT_DIR = "./public/photos/gallery";
const MANIFEST_OUT = "./src/data/photos.ts";

interface Tier {
  name: string;
  width: number;
  height: number;
  quality: number;
}

const TIERS: Tier[] = [
  { name: "thumb", width: 400, height: 267, quality: 75 },
  { name: "display", width: 1200, height: 800, quality: 82 },
  { name: "full", width: 2400, height: 1600, quality: 85 },
];

const VALID_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp", ".tiff"]);

async function main() {
  console.log("Reading source photos...");
  const allFiles = await readdir(SOURCE_DIR);

  // Filter: only image files, exclude duplicates (副本)
  const photos = allFiles.filter((f) => {
    const ext = extname(f).toLowerCase();
    if (!VALID_EXTENSIONS.has(ext)) return false;
    if (f.includes("副本")) {
      console.log(`  Skipping duplicate: ${f}`);
      return false;
    }
    // Check if a non-副本 version also exists — skip the 副本 one
    const base = f.replace(/ - 副本/, "");
    if (f.includes(" - 副本") && allFiles.includes(base)) {
      console.log(`  Skipping duplicate (original exists): ${f}`);
      return false;
    }
    return true;
  });

  // Deduplicate by checking for files where both 副本 and non-副本 exist
  const baseNames = new Set(photos.map((f) => f.replace(/ - 副本/, "")));
  const uniquePhotos = photos.filter((f) => {
    const base = f.replace(/ - 副本/, "");
    // If we already have the same file without 副本, skip
    if (f.includes(" - 副本")) return false;
    return true;
  });

  console.log(`\nFound ${uniquePhotos.length} unique photos (from ${allFiles.length} total files)\n`);

  // Create output directories
  for (const tier of TIERS) {
    await mkdir(join(OUTPUT_DIR, tier.name), { recursive: true });
  }

  // Process each photo
  const processed: string[] = [];
  let completed = 0;
  const total = uniquePhotos.length;

  for (const filename of uniquePhotos) {
    const srcPath = join(SOURCE_DIR, filename);
    const name = parse(filename).name.toLowerCase();

    try {
      // Check file size to skip corrupt/small files
      const fileStat = await stat(srcPath);
      if (fileStat.size < 1000) {
        console.log(`  [${++completed}/${total}] Skipping small file: ${filename}`);
        continue;
      }

      for (const tier of TIERS) {
        const outPath = join(OUTPUT_DIR, tier.name, `${name}.webp`);
        await sharp(srcPath)
          .rotate()
          .resize(tier.width, tier.height, { fit: "cover", position: "center" })
          .webp({ quality: tier.quality })
          .toFile(outPath);
      }
      processed.push(name);
      console.log(`  [${++completed}/${total}] Processed: ${filename}`);
    } catch (err) {
      console.error(`  [${++completed}/${total}] Error processing ${filename}:`, err instanceof Error ? err.message : err);
    }
  }

  console.log(`\nSuccessfully processed ${processed.length} photos.\n`);

  // Generate manifest
  const manifest = `export interface Photo {
  filename: string;
  alt: string;
}

// Auto-generated by scripts/process-photos.ts
// ${processed.length} photos — ${new Date().toISOString()}
export const photos: Photo[] = [
${processed.map((f) => `  { filename: "${f}", alt: "" }`).join(",\n")}
];
`;

  await writeFile(MANIFEST_OUT, manifest, "utf-8");
  console.log(`Manifest written to ${MANIFEST_OUT}`);
  console.log("Done!");
}

main().catch(console.error);
